### PR TITLE
Properly handle failure to parse right side of binary operations

### LINKED ISSUE #305: "Attempt to assign property 'parent' of non-object" on malformed code
Feeding the input `<?\&static\` into the parser results in:

```
Error: Attempt to assign property 'parent' of non-object in /home/nikic/tolerant-php-parser/src/Parser.php:2026
Stack trace:
#0 /home/nikic/tolerant-php-parser/src/Parser.php(1877): Microsoft\PhpParser\Parser->makeBinaryExpression(Object(Microsoft\PhpParser\Node\QualifiedName), Object(Microsoft\PhpParser\Token), NULL, NULL, Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement))
#1 /home/nikic/tolerant-php-parser/src/Parser.php(1648): Microsoft\PhpParser\Parser->parseBinaryExpressionOrHigher(0, Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement))
#2 /home/nikic/tolerant-php-parser/src/Parser.php(581): Microsoft\PhpParser\Parser->parseExpression(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement), true)
#3 /home/nikic/tolerant-php-parser/src/Parser.php(199): Microsoft\PhpParser\Parser->Microsoft\PhpParser\{closure}(Object(Microsoft\PhpParser\Node\SourceFileNode))
#4 /home/nikic/tolerant-php-parser/src/Parser.php(165): Microsoft\PhpParser\Parser->parseList(Object(Microsoft\PhpParser\Node\SourceFileNode), 0)
#5 /home/nikic/PHP-Fuzzer/example/target_tolerant_php_parser.php(15): Microsoft\PhpParser\Parser->parseSourceFile('<?\\&static\\\n')
```

Ran into this while testing a fuzzer.

### PR DESCRIPTION
**Pull request by TysonAndre**
Fixes #305

### CODE REVIEW

File: src/Parser.php [hunk 1]
```diff
@@ -1068,10 +1068,9 @@ private function parsePrimaryExpression($parentNode) {
             // anonymous-function-creation-expression
             case TokenKind::StaticKeyword:
                 // handle `static::`, `static(`, `new static;`, `instanceof static`
-                if (($this->lookahead([TokenKind::ColonColonToken, TokenKind::OpenParenToken])) ||
-                    (!$this->lookahead([TokenKind::FunctionKeyword, TokenKind::FnKeyword]))
-                ) {
-                    return $this->parseQualifiedName($parentNode);
+                if ((!$this->lookahead([TokenKind::FunctionKeyword, TokenKind::FnKeyword]))) {
```
Comment (roblourens) [inline src/Parser.php]: unnecessary set of parens

Comment (roblourens) [inline src/Parser.php]:
```suggestion
                if (!$this->lookahead([TokenKind::FunctionKeyword, TokenKind::FnKeyword])) {
```

Comment (roblourens) [reply src/Parser.php]: Will fix after merging
